# 配置端口
server:
  port: 8686
  servlet:
    session:
      timeout: 21600s

# 配置mysql数据库
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.71.220.35:3306/blog?serverTimezone=Asia/Shanghai&allowMultiQueries=true
#    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 30000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 30000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  # redis配置
  redis:
    host: 124.71.220.35
    port: 6379
    password:
  # mq配置
  rabbitmq:
    host: 124.71.220.35
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3 #最大重试次数
          initial-interval: 3000s #重试间隔时间（单位毫秒）
      direct:
        auto-startup: true
  # es配置 若搜索模式为mysql可删除
  elasticsearch:
    rest:
      uris: 124.71.220.35:9200
  # 邮箱配置
  mail:
    host: smtp.qq.com
    username: 870900860@qq.com
    password: gtbpocccjufebbgh
    default-encoding: UTF-8
    port: 587
    properties:
      mail:
      smtp:
      auth: true
      socketFactory:
      class: javax.net.ssl.SSLSocketFactory
  # 上传图片大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size:  100MB

# 配置MybatisPlus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
# 关闭一级缓存statement，开启是session
#    local-cache-scope: statement
    #关闭二级缓存false，开启是true
#    cache-enabled: false

# 搜索模式 可选 elasticsearch或mysql
search:
  mode: elasticsearch
#  mode: mysql


# 上传模式 可选 oss或local  （http://和最后的/一定不能去！！！）
upload:
  mode: local
  local:
    # nginx映射本地文件路径，无域名则为 ip:83
    url: http://124.71.220.35:83/
    # 本地文件存储路径
    path: /usr/local/upload/
#    path: D:\luziling\Vueprojects\demo\blog\blog-springboot\src\main\resources\imgavatar\

  oss:
    url: https://bishestore.oss-cn-heyuan.aliyuncs.com/
    endpoint: oss-cn-heyuan.aliyuncs.com
    accessKeyId:
    accessKeySecret:
    bucketName: bishestore
  cos:
    url: http://Bucket域名/
    secretId: cos的secretId
    secretKey: cos的secretKey
    region: cos的region
    bucketName: cos的bucketName

# 网站前台域名（邮件通知用）
website:
  url: http://124.71.220.35

#第三方配置信息
qq:
  app-id: QQ APPID
  check-token-url: https://graph.qq.com/oauth2.0/me?access_token={access_token}
  user-info-url: https://graph.qq.com/user/get_user_info?openid={openid}&access_token={access_token}&oauth_consumer_key={oauth_consumer_key}

weibo:
  app-id: 微博APPID
  app-secret: 微博APPSECRET
  grant-type: authorization_code
  redirect-url: 微博回调地址
  access-token-url: https://api.weibo.com/oauth2/access_token
  user-info-url: https://api.weibo.com/2/users/show.json?uid={uid}&access_token={access_token}

# https://gitee.com/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&response_type=code&scope=user_info
# https://gitee.com/oauth/token?grant_type=authorization_code&code={code}&client_id={client_id}&redirect_uri={redirect_uri}&client_secret={client_secret}
# 回调地址为前端首页url地址

gitee:
  client-id: abdbbec7723f60e014b87ecccdc5502b5b637526c0ead56ee620e19c72652da7
  client-secret: 3827f5d7df3acaa8c9adacdb6714bb7622ad8930df13e06edd94583e6787b954
  grant-type: authorization_code
  redirect-url: http://124.71.220.35:80/oauth/login/gitee
  access-token-url: https://gitee.com/oauth/token
  user-info-url: https://gitee.com/api/v5/user?access_token={access_token}

